name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test concat
      run: ./concat_all.py && git diff --exit-code
    - name: Build
      run: cargo build --verbose
    - name: Build manual initialized version
      run: cargo build --verbose --features=manual-init
    - name: Test
      run: cd tests; cargo test
